# this file was changed
MODEL:
  WEIGHTS: '' 
compute_precision:
  grad_scaler: true
  teacher:
    backbone:
      sharding_strategy: SHARD_GRAD_OP
      mixed_precision:
        param_dtype: fp16
        reduce_dtype: fp16
        buffer_dtype: fp32
    dino_head:
      sharding_strategy: SHARD_GRAD_OP
      mixed_precision:
        param_dtype: fp16
        reduce_dtype: fp16
        buffer_dtype: fp32
    ibot_head:
      sharding_strategy: SHARD_GRAD_OP
      mixed_precision:
        param_dtype: fp16
        reduce_dtype: fp16
        buffer_dtype: fp32
  student:
    backbone:
      sharding_strategy: SHARD_GRAD_OP
      mixed_precision:
        param_dtype: fp16
        reduce_dtype: fp16
        buffer_dtype: fp32
    dino_head:
      sharding_strategy: SHARD_GRAD_OP
      mixed_precision:
        param_dtype: fp16
        reduce_dtype: fp32
        buffer_dtype: fp32
    ibot_head:
      sharding_strategy: SHARD_GRAD_OP
      mixed_precision:
        param_dtype: fp16
        reduce_dtype: fp32
        buffer_dtype: fp32
dino:
  loss_weight: 1.0 # 1.0 original
  head_n_prototypes: 65536
  head_bottleneck_dim: 256
  head_nlayers: 3
  head_hidden_dim: 2048
  koleo_loss_weight: 0.05
ibot:
  loss_weight: 0.3 # 1.0 original
  mask_sample_probability: 0.4
  mask_ratio_min_max:
  - 0.1
  - 0.4
  separate_head: false
  head_n_prototypes: 65536
  head_bottleneck_dim: 256
  head_nlayers: 3
  head_hidden_dim: 2048
train:
  use_fsdp: true
  batch_size_per_gpu: 112 # 112 for full, 200 for 4 blocks
  
  dataset_path: CustomImageDataset:split=TRAIN:root=/workspace/data/images/:extra=/workspace/data/paths_no_anno.csv:yolo_bbox_path=/workspace/data/post_id_path_to_yolov9e_bbox.json
  output_dir: data/runs/dino_training/ # change to something reasonable
  exp_name: vitl_bs112_all_data_e45_oel3k_le5e-5__less_color__yolov9e__fullft
  freeze_but_last: 0
  saveckp_freq: 2
  seed: 0
  
  num_workers: 8  # !!!!!!!!!!!!!!!!!!!!!!!!!!
  
  OFFICIAL_EPOCH_LENGTH: 3000
  cache_dataset: true
  centering: "sinkhorn_knopp" # or "sinkhorn_knopp" or "centering"
student:
  arch: vit_large # e.g. vit_large or vit_small or vit_giant2
  patch_size: 14 # important to use the checkpoints!
  drop_path_rate: 0.
  layerscale: 1.0e-05
  drop_path_uniform: true # original true
  pretrained_weights: 
  ffn_layer: "mlp" #"swiglufused" or "mlp"
  block_chunks: 0
  qkv_bias: true
  proj_bias: true
  ffn_bias: true
  num_register_tokens: 0y
  interpolate_antialias: false
  interpolate_offset: 0.1
teacher:
  momentum_teacher: 0.996
  final_momentum_teacher: 1
  warmup_teacher_temp: 0.04
  teacher_temp: 0.07
  warmup_teacher_temp_epochs: 20 # original was 30
optim:
  epochs: 45 #200 for bs 256
  weight_decay: 0.04 # 0.04 original
  weight_decay_end: 0.1
  base_lr: 5.0e-05  # learning rate for a batch size of 1024 is 2.0e-04
  lr: 0.  # will be set after applying scaling rule
  warmup_epochs: 4
  min_lr: 1.0e-06
  clip_grad: 3.0
  freeze_last_layer_epochs: 1 #original 1
  scaling_rule: sqrt_wrt_1024
  patch_embed_lr_mult: 0.1
  layerwise_decay: 0.75
  adamw_beta1: 0.9
  adamw_beta2: 0.999
crops:
  global_crops_scale:
  - 0.5
  - 1.0
  local_crops_number: 2
  local_crops_scale:
  - 0.05
  - 0.32
  global_crops_size: 224 #original 224 -> 518 necessary for loading checkpoints, however, interpolation can be used to adapt the size
  local_crops_size: 98 #original 96 -> has to be divideable by 14
evaluation:
  eval_period_iterations: 9000 # original 12500, what better -> use 1000 for finetuning
# add a link to an /eval/training_iterations here, to continue with training to load the dino head weights as well, important: also set the start iterations!
head:
  head_path:
